Rwc2019
tue-robotics/ed_sensor_integration pull request #25
Opened 2019-08-20 18:33 UTC by PetervDooren

2019-08-20 20:01 UTC, MatthijsBurgh commented on src/kinect/ray_tracer.cpp
> +  lrf.setNumBeams(2); // Because of Matthijs geolib refactor
This should be fixed by https://github.com/tue-robotics/geolib2/pull/30

2019-08-20 20:07 UTC, MatthijsBurgh requested changes

2019-08-20 20:07 UTC, MatthijsBurgh commented on src/kinect/ray_tracer.cpp
> +//    opt.setMesh(e->shape()->getBoundingBox().getMesh(), raytrace_pose.inverse() * e->pose()); // Use bbx
Remove commented code

2019-08-20 20:07 UTC, MatthijsBurgh commented on src/kinect/ray_tracer.cpp
> +        res.active_entity_ = e->id().str();
res could be set once.

2019-09-03 19:12 UTC, MatthijsBurgh commented on src/kinect/ray_tracer.cpp
> +  lrf.setNumBeams(2); // Because of Matthijs geolib refactor
Reverted as https://github.com/tue-robotics/geolib2/pull/30 is merged.

2019-09-09 11:32 UTC, LoyVanBeek submitted a review, later dismissed
OK overall, but some cleanup needed

2019-09-09 11:32 UTC, LoyVanBeek commented on src/kinect/kinect_plugin.cpp
> +    static int iter = 0;
Huh? Why this?

2019-09-09 11:32 UTC, LoyVanBeek commented on src/kinect/kinect_plugin.cpp
> +        // ToDo: RoboCup hack
Can be removed right?

2019-09-17 19:11 UTC, MatthijsBurgh commented on src/kinect/kinect_plugin.cpp
> +    static int iter = 0;
indent fix only

2019-09-17 19:12 UTC, MatthijsBurgh approved these changes

2019-09-17 19:13 UTC, MatthijsBurgh commented on src/kinect/kinect_plugin.cpp
> +        // ToDo: RoboCup hack
Removed

2019-09-17 20:11 UTC, merged