Feature/test tools: refactored 'Fitter'
tue-robotics/ed_sensor_integration pull request #38
Opened 2020-12-12 15:01 UTC by jlunenburg

2021-02-06 15:01 UTC, PetervDooren requested changes
I know that it is not the focus of this PR but I think it would be a good idea to add docstrings to some ot the classes. Explain what they are and what the functions do. In case of the main function it is also a good idea to explain what the process is.
Other than that this thing is beautiful

2021-02-06 15:01 UTC, PetervDooren commented on ed_sensor_integration/src/kinect/fitter.cpp
> +                                   const geo::Pose3D& expected_pose, geo::Pose3D& fitted_pose, double max_yaw_change) const
I know that adding docstrings is not the focus of this PR. But a docstring explaining this function would help a lot. There we can explain the process that is used to estimate the entitiy-pose. We can explain among other things how we determine the candidates, i.e. what we are iterating over. It can explain the definition of the yaw angle (w.r.t. what is it defined).

2021-02-06 15:01 UTC, PetervDooren commented on ed_sensor_integration/src/kinect/fitter.cpp
> +    double error_threshold = 1e5;
is there a way to relate this magic number to the one of the initial current_optimum. That would save us one magic number

2021-02-06 15:01 UTC, PetervDooren commented on ed_sensor_integration/include/ed/kinect/fitter.h
> +    EntityRepresentation2D GetOrCreateEntity2D(const ed::EntityConstPtr& e) const;
resolve your own TODO.

2021-02-06 15:01 UTC, PetervDooren commented on ed_sensor_integration/include/ed/kinect/fitter.h
> +                      std::vector<double>& model_ranges, std::vector<int>& identifiers) const;
resolve own TODO

2021-02-06 15:01 UTC, PetervDooren commented on ed_sensor_integration/include/ed/kinect/fitter.h
> +                   const geo::Pose3D& expected_pose, geo::Pose3D& fitted_pose, double max_yaw_change) const;
For this one and many in this class definition:
Should this be in the header file? or can we simply put it in the code file. Especially private functions might not be needed anywhere outside this class.

2021-02-06 15:01 UTC, PetervDooren commented on ed_sensor_integration/src/kinect/fitter.cpp
> +        double dm = test_ranges[i];
These represent the distance according to the sensor and model, correct? perhaps add a comment to clarify this.

2021-02-06 15:01 UTC, PetervDooren commented on ed_sensor_integration/src/kinect/fitter.cpp
> +        }
ideally we would have a lot less magic numbers in this scoring system. But I acknowledge that that is not the purpose of this PR.

2021-02-06 15:01 UTC, PetervDooren commented on ed_sensor_integration/test/test_furniture_fit.cpp
> + */
I am fine with leaving this TODO for another PR. Was this your intention?

2021-02-07 12:41 UTC, MatthijsBurgh requested changes

2021-02-07 12:41 UTC, MatthijsBurgh commented on ed_sensor_integration/src/kinect/fitter.cpp
> +    geo::Vec3 expected_pos_SENSOR = data.sensor_pose_xya.inverse() * expected_pose.t;
Why these caps? Doesn't match any naming/case convention

2021-02-07 12:41 UTC, MatthijsBurgh commented on ed_sensor_integration/include/ed/kinect/fitter.h
> +    EstimationInputData preProcessInputData(const ed::WorldModel &world, const ed::UUID &id, const geo::Pose3D &expected_pose, const FitterData &data) const; // ToDo: unique_ptr?
Unique_ptr to what?

2021-02-09 19:11 UTC, jlunenburg commented on ed_sensor_integration/include/ed/kinect/fitter.h
> +                   const geo::Pose3D& expected_pose, geo::Pose3D& fitted_pose, double max_yaw_change) const;
That's true, but class functions must be declared in the class definition, hence here. If free functions would be used, you could indeed declare them in the source file. However, you wouldn't have access to the member variables in that case.

2021-02-09 19:15 UTC, jlunenburg commented on ed_sensor_integration/src/kinect/fitter.cpp
> +        }
Yes, I tried to change as little as possible content wise. Therefore, I consider this outside the scope

2021-02-09 19:15 UTC, jlunenburg commented on ed_sensor_integration/test/test_furniture_fit.cpp
> + */
Yes, this might become important once we add more tests.

2021-02-09 19:18 UTC, jlunenburg commented on ed_sensor_integration/src/kinect/fitter.cpp
> +                                   const geo::Pose3D& expected_pose, geo::Pose3D& fitted_pose, double max_yaw_change) const
See e2ef22e71db426461225079a85e07b267bddafbc

2021-02-09 19:19 UTC, jlunenburg commented on ed_sensor_integration/src/kinect/fitter.cpp
> +    double error_threshold = 1e5;
See 8e3b620eb4aadc116630c04fb806cdf23702a7af

2021-02-09 19:19 UTC, jlunenburg commented on ed_sensor_integration/include/ed/kinect/fitter.h
> +    EntityRepresentation2D GetOrCreateEntity2D(const ed::EntityConstPtr& e) const;
See e2ef22e71db426461225079a85e07b267bddafbc

2021-02-09 19:19 UTC, jlunenburg commented on ed_sensor_integration/include/ed/kinect/fitter.h
> +                      std::vector<double>& model_ranges, std::vector<int>& identifiers) const;
See e2ef22e71db426461225079a85e07b267bddafbc

2021-02-09 19:19 UTC, jlunenburg commented on ed_sensor_integration/src/kinect/fitter.cpp
> +        double dm = test_ranges[i];
See b6f1d89877f5c398adca0fc5e7be1c4f94a42dd5

2021-02-09 19:19 UTC, jlunenburg commented on ed_sensor_integration/src/kinect/fitter.cpp
> +    geo::Vec3 expected_pos_SENSOR = data.sensor_pose_xya.inverse() * expected_pose.t;
See b6f1d89877f5c398adca0fc5e7be1c4f94a42dd5

2021-02-09 19:20 UTC, jlunenburg commented on ed_sensor_integration/include/ed/kinect/fitter.h
> +    EstimationInputData preProcessInputData(const ed::WorldModel &world, const ed::UUID &id, const geo::Pose3D &expected_pose, const FitterData &data) const; // ToDo: unique_ptr?
Removed, not sure how to improve

2021-02-09 19:23 UTC, jlunenburg commented
I found a potential bug, need to investigate

2021-02-09 20:21 UTC, PetervDooren reviewed
Needs to be tested on the robot. Then It is good as far as I'm concerned

2021-02-09 20:21 UTC, PetervDooren submitted a review, later dismissed

2021-02-10 16:00 UTC, MatthijsBurgh submitted a review, later dismissed

2021-02-19 13:28 UTC, PetervDooren commented
When tested this gave the compile error:

> /home/amigo/ros/melodic/system/src/ed_robocup/src/plugin.cpp: In member function ‘bool RobocupPlugin::srvFitEntityInImage(ed_robocup_msgs::FitEntityInImage::Request&, ed_robocup_msgs::FitEntityInImage::Response&)’:
> /home/amigo/ros/melodic/system/src/ed_robocup/src/plugin.cpp:353:49: error: ‘class Fitter’ has no member named ‘GetOrCreateEntity2D’; did you mean ‘getOrCreateEntity2D’?
>          EntityRepresentation2D repr2d = fitter_.GetOrCreateEntity2D(e);
>                                                  ^~~~~~~~~~~~~~~~~~~
>                                                  getOrCreateEntity2D

2021-02-19 14:27 UTC, PetervDooren submitted a review, later dismissed

2021-02-19 15:14 UTC, MatthijsBurgh reviewed
The function @PetervDooren mentioned, should be made public again. I think that is easiest solution to keep `ed_robocup` working

2021-02-19 15:17 UTC, PetervDooren commented
I think we first need to wonder whether ed_robocup is abusing the function. Because this does not seem like something the fitter should be providing.

2021-02-23 18:29 UTC, jlunenburg commented
> When testing the system could not compile. It gave an error in ed_robocup, which makes use of fitter::getOrCreateEntity2D, which has been made private in this PR.
> 
> So we gotta make sure that ed_robocup is also compatible with this update
> 
> Other than that, works like a charm in the real world

@PetervDooren I rolled it back and made it public again. Not sure how much work it'd be to fix it in `ed_robocup` and feel that this has taken long enough ;-)

2021-02-23 18:54 UTC, PetervDooren approved these changes

2021-02-23 18:57 UTC, merged