Allow worldmodel and entity input
tue-robotics/ed_sensor_integration pull request #50
Opened 2021-11-16 20:05 UTC by PetervDooren

2021-11-17 09:30 UTC, MatthijsBurgh requested changes
I expected better of you @PetervDooren after our talk about styleguides 😉

We are changing a current tool. What was the old tool doing and is the new behaviour similar? Or has the tool completely changed? In that case we are actually removing a tool and creating a new one. And we should have a valid reason to drop the old one.

2021-11-17 09:30 UTC, MatthijsBurgh commented on ed_sensor_integration/tools/segmenter.cpp
> +        }
```suggestion
        if (argc == 2)
        {
            std::cout << "No worldmodel provided! Using empty worldmodel and no segmentation area" << std::endl;
        }
        else
        {
            usage();
            return 1;
        }
```

2021-11-17 09:30 UTC, MatthijsBurgh commented on ed_sensor_integration/tools/segmenter.cpp
> +    if (argc == 4) {
```suggestion
    if (argc == 4)
    {
```

2021-11-17 09:30 UTC, MatthijsBurgh commented on ed_sensor_integration/tools/segmenter.cpp
> +        if (!loadWorldModel(model_name, world_model)){
```suggestion
        if (!loadWorldModel(model_name, world_model))
        {
```

2021-11-17 09:30 UTC, MatthijsBurgh commented on ed_sensor_integration/tools/segmenter.cpp
> +                std::cout << "area description" << snapshot.area_description << std::endl;
```suggestion
                snapshot.world_model = world_model;
                if (e)
                    snapshot.area_description = std::string("on_top_of ").append(entity_id);
                else
                    snapshot.area_description = "";

                std::cout << "area description" << snapshot.area_description << std::endl;
```
Better to see what is in the `else` and what not.

2021-11-17 09:33 UTC, PetervDooren commented
The old behaviour of this tool is maintained. Hence the option to provide only 2 arguments instead of 4. As for style guides. We didn't get to that lecture yet :p

2021-11-17 12:02 UTC, MatthijsBurgh commented on ed_sensor_integration/tools/segmenter.cpp
> +        if (!loadWorldModel(model_name, world_model))
```suggestion

        if (!loadWorldModel(model_name, world_model))
```

2021-11-17 12:04 UTC, MatthijsBurgh commented
In the old code I see `annotations`, but this is nowhere in the new code.

2021-12-18 13:44 UTC, closed without merging

2021-12-18 13:45 UTC, PetervDooren commented
closed as these issues were adressed in PR #49